name: Build with spack cache
description: |
  Build mucoll stack with spack cache.
  This workflow is triggered by the mucoll-spack repository.
  It builds the stack and pushes the binaries to the cache.

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest
    container: ghcr.io/key4hep/key4hep-externals-${{inputs.os}}:main
    steps:
      - name: Checkout mucoll repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
          path: mucoll-spack
      - name: Spack Setup Build Cache
        run: |
          . /opt/setup_spack.sh
          spack config add 'config:install_tree:padded_length:128'
          spack mirror add --oci-username '${{ github.actor }}' --oci-password '${{ secrets.GITHUB_TOKEN }}' --unsigned --autopush local-buildcache 'oci://ghcr.io/${{ github.repository_owner }}/mucoll-buildcache'
      - name: Apply Patches
        run: |
          whereami=$(pwd)
          cd /opt/spack 
          . ${whereami}/mucoll-spack/.cherry-pick
          cd -
      - name: Spack Repo Setup
        run: |
          . /opt/setup_spack.sh
          spack --version
          spack repo add /opt/spack/var/key4hep-spack
          spack repo add mucoll-spack
          spack compiler find
      - name: Spack concretize
        run: |
          . /opt/setup_spack.sh
          spack env activate mucoll-spack/environments/mucoll-release
          spack concretize --reuse      
      #- name: Spack Build mucoll-release
      #  run: |
      #    . /opt/setup_spack.sh
      #    spack env activate mucoll-spack/environments/mucoll-release
      #    spack concretize --reuse
      #    spack install --only-concrete --no-add --fail-fast
      #    spack clean -a