name: concretize-ubuntu

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Spack
        uses: actions/checkout@v3
        with:
          repository: spack/spack
          path: spack

      - name: Checkout Key4hep
        uses: actions/checkout@v3
        with:
          repository: key4hep/key4hep-spack
          path: key4hep-spack

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: mucoll-spack

      - name: Concretize mucoll-stack
        run: |
          source spack/share/spack/setup-env.sh
          spack repo add key4hep-spack
          spack repo add mucoll-spack
          spack compiler find
          spack env activate mucoll-spack/environments/mucoll-common/
          spack concretize  | tee -a ${GITHUB_WORKSPACE}/key4hep-stack-concretization.log
