name: concretize-ubuntu

on: [push, pull_request]

jobs:
  concretize-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Spack
        uses: actions/checkout@v3
        with:
          repository: spack/spack
          path: spack

      - name: Checkout Key4hep
        uses: actions/checkout@v3
        with:
          repository: key4hep/key4hep-spack
          path: key4hep-spack

      - name: Checkout this repo
        uses: actions/checkout@v3
        with:
          path: mucoll-spack

      - name: Concretize mucoll-common
        run: |
          source spack/share/spack/setup-env.sh
          spack repo add key4hep-spack
          spack repo add mucoll-spack
          spack compiler find
          spack env activate mucoll-spack/environments/mucoll-common/
          spack add mucoll-stack %gcc@11:
          spack concretize
          spack spec -Nt > ${GITHUB_WORKSPACE}/spec-common.log

      - name: Concretize mucoll-release
        run: |
          source spack/share/spack/setup-env.sh
          spack env activate mucoll-spack/environments/mucoll-release/
          spack add mucoll-stack %gcc@11:
          spack concretize
          spack spec -Nt > ${GITHUB_WORKSPACE}/spec-release.log
