name: Re-build and publish all
on:
  push:
    paths:
        - 'AlmaLinux9/Dockerfile-spack'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'
      - 'main'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write
  id-token: write
  attestations: write

jobs:
  build-spack:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [{dir: AlmaLinux9,suffix: alma9}]
    env:
      IMAGE_NAME: mucoll-spack
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Make owner name lowercase
        run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
            OWNER: '${{ github.repository_owner }}'
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{env.OWNER_LC}}/mucoll-dummy
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-spack
          push: true
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ env.REGISTRY }}/${{env.OWNER_LC}}
          tags: ${{ env.REGISTRY }}/${{env.OWNER_LC}}/${{ env.IMAGE_NAME}}:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
          labels: ${{ steps.meta.outputs.labels }}
  build-minimal:
    runs-on: ubuntu-latest
    needs: build-spack
    strategy:
      matrix:
        os: [{dir: AlmaLinux9,suffix: alma9}]
    env:
      IMAGE_NAME: mucoll-minimal
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: lowercase owner name
        run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
            OWNER: '${{ github.repository_owner }}'
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{env.OWNER_LC}}/mucoll-dummy
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-minimal
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ env.REGISTRY }}/${{env.OWNER_LC}}
          tags: ${{ env.REGISTRY }}/${{env.OWNER_LC}}/${{ env.IMAGE_NAME}}:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
          labels: ${{ steps.meta.outputs.labels }}
  build-sim:
    runs-on: ubuntu-latest
    needs: build-minimal
    strategy:
      matrix:
        os: [{dir: AlmaLinux9,suffix: alma9}]
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: lowercase owner name
        run: |
            echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
            OWNER: '${{ github.repository_owner }}'
      - name: Docker Meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{env.OWNER_LC}}/mucoll-dummy
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./${{matrix.os.dir}}
          file: ./${{matrix.os.dir}}/Dockerfile-sim
          build-args: |
            VERSION=${{ steps.meta.outputs.version }}
            REPOSITORY=${{ env.REGISTRY }}/${{env.OWNER_LC}}
          tags: ${{ env.REGISTRY }}/${{env.OWNER_LC}}/mucoll-sim:${{steps.meta.outputs.version}}-${{matrix.os.suffix}}
